site_name: Hot100 算法笔记

theme:
  name: material
  language: zh

plugins:
  - search
  - mkdocs-jupyter

nav:
nav:
  - 首页: index.md
  - Notebooks:
      - 哈希表: notebooks/哈希表.ipynb
      - 链表: notebooks/链表.ipynb
      - 排序: notebooks/排序.ipynb
      - 数组: notebooks/数组.ipynb
      - 双指针: notebooks/双指针.ipynb